services:

  simple:
    image: michael/simple
    container_name: simple
    build: .simple/
    env_file: ".env"
    restart: on-failure

  builder:
    image: michael/builder
    container_name: builder
    build: .builder/
    depends_on: 
      - simple
    env_file: ".env"
    restart: on-failure

  mod_tile:
    container_name: mod_tile
    volumes: 
      - MOD:/tmp/
      - CGI:/var/www/cgi-bin/
      - MAP:/.MAP
      - DB_CONN:/home/owmuser/db_connect/
    networks: ["OWM_network"]
    build: mod_tile/
    env_file: ".env"
    restart: on-failure

#  mapnik:
#    container_name: mapnik
#    volumes: 
#      - MAP:/.MAP
#      - MAP_inc:/usr/include
#    networks: ["OWM_network"]
#    build: mapnik/
#    depends_on: 
#      - builder 
#    env_file: ".env"
#    restart: on-failure
#
  osm2pgsql:
    container_name: osm2pgsql
    volumes: 
      - PBF:/.PBF/
    networks: ["OWM_network"]
    build: osm2pgsql/
    depends_on: 
      - builder 
    env_file: ".env"
    restart: on-failure

  postgres:
    container_name: postgres
    volumes: 
      - DB:/var/lib/postgresql/
    networks: ["OWM_network"]
    build: postgres/
    depends_on: 
      - simple
    env_file: ".env"
    restart: on-failure

volumes:
  DB:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: $HOME/.docker/OWM/DB/
  PBF:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: $HOME/.docker/OWM/PBF/
  MOD:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: $HOME/.docker/OWM/MOD/
  MAP:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: $HOME/.docker/OWM/MAP/
  CGI:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: $HOME/.docker/OWM/CGI/
  DB_CONN:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: $HOME/.docker/OWM/DB_CONN/

networks:
  OWM_network:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
