services:

  simple:
    image: michael/simple
    container_name: simple
    build: .simple/
    env_file: ".env"
    restart: on-failure

  builder:
    image: michael/builder
    container_name: builder
    build: .builder/
    depends_on: 
      - simple
    env_file: ".env"
    restart: on-failure

###############################################################

  mod_tile:
    container_name: mod_tile
    volumes: 
      - MOD:/tmp/
      - MAP:/.MAP
      - DB_CONN:/home/${DB_USER}/db_connect/
      - WWW:/var/www/
    networks: ["OWM_network"]
    dns:
      - 8.8.8.8
    build:
      context: mod_tile/ 
      args:
        DB_USER: ${DB_USER}
        G_MESSAGES_DEBUG: ${G_MESSAGES_DEBUG}
    ports: 
      - 80:8080
    depends_on: 
      - postgres 
    env_file: ".env"
    restart: on-failure

  osm2pgsql:
    container_name: osm2pgsql
    volumes: 
      - PBF:/.PBF/
    networks: ["OWM_network"]
    dns:
      - 8.8.8.8
    build: osm2pgsql/
    depends_on: 
      - builder 
    env_file: ".env"
    restart: on-failure

  postgres:
    container_name: postgres
    volumes: 
      - DB:/var/lib/postgresql/
    networks: ["OWM_network"]
    build: postgres/
    depends_on: 
      - simple
    env_file: ".env"
    restart: on-failure

volumes:
  DB:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: $HOME/.docker/OWM/DB/
  WWW:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: $HOME/.docker/OWM/WWW/
  DB_CONN:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: $HOME/.docker/OWM/DB_CONN/
  PBF:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: $HOME/.docker/OWM/PBF/
  MOD:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: $HOME/.docker/OWM/MOD/
  MAP:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: $HOME/.docker/OWM/MAP/

networks:
  OWM_network:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
