services:

  mapnik:
    container_name: mapnik
    volumes: 
      - MAP:/.MAP/
    networks: ["OWM_network"]
    build: mapnik/
#    depends_on: 
#      - osm2pgsql
    env_file: ".env"
    restart: on-failure

  osm2pgsql:
    container_name: osm2pgsql
    volumes: 
      - PBF:/.PBF/
    networks: ["OWM_network"]
    build: osm2pgsql/
#    depends_on: 
#      - postgres
    env_file: ".env"
    restart: on-failure

  postgres:
    container_name: postgres
    volumes: 
      - DB:/var/lib/postgresql/
    networks: ["OWM_network"]
    build: postgres/
    env_file: ".env"
    restart: on-failure

volumes:
  DB:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: $HOME/.docker/OWM/DB/
  PBF:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: $HOME/.docker/OWM/PBF/
  MAP:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: $HOME/.docker/OWM/MAP/

networks:
  OWM_network:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
